# my global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'miner_exporters'
    static_configs:
    - targets: ['172.28.5.45:9825','172.28.5.46:9825','172.28.5.47:9825','172.28.5.48:9825','172.28.5.49:9825','172.28.5.50:9825','172.28.5.51:9825','172.28.5.52:9825','172.28.5.53:9825','172.28.5.54:9825','172.28.5.55:9825','172.28.5.56:9825','172.28.5.57:9825','172.28.5.58:9825','172.28.5.59:9825','172.28.5.60:9825','172.28.5.61:9825','172.28.5.62:9825','172.28.5.63:9825','172.28.5.64:9825']

  - job_name: 'node'
    static_configs:
    - targets: ['51.81.113.208:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5m
    scrape_timeout: 1m
    static_configs:
    - targets: ['51.81.113.208:8080']
    tls_config:
      insecure_skip_verify: true
