# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'miner_exporter'
    static_configs:
    - targets: ['51.81.113.208:9825','51.81.113.223:9100']

  - job_name: 'node'
    static_configs:
    - targets: ['51.81.113.208:9100','51.81.113.223:9100']

'135.148.35.41','51.81.113.208','51.81.113.209','51.81.113.210','51.81.113.211','51.81.113.212','51.81.113.213','51.81.113.214','51.81.113.215','51.81.113.216','51.81.113.217','51.81.113.218','51.81.113.219','51.81.113.220','51.81.113.221','51.81.113.222','51.81.113.223','135.148.129.208','135.148.129.209','135.148.129.210','135.148.129.211','135.148.129.212','135.148.129.213','135.148.129.214','135.148.129.215'